{
 "title": "Automated-Backup",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  {
   "title": "Last Execution",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT TO_CHAR(MAX(data_iniz), 'DD/MM/YYYY HH24:MI') from py_monitor.elaborazioni\r\nwhere script_name = 'automated-backup'"
    }
   ]
  },
  {
   "title": "Last Run",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n    EXTRACT(MINUTE FROM (MAX(data_fine) - MAX(data_iniz))) || ' min '||\r\n    round(EXTRACT(SECOND FROM (MAX(data_fine) - MAX(data_iniz))),0) || ' sec'\r\nFROM \r\n    py_monitor.elaborazioni\r\nWHERE \r\n    script_name = 'automated-backup';"
    }
   ]
  },
  {
   "title": "Last Dimension",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select size AS FullBackup\r\nfrom py_monitor.elaborazioni_size\r\nwhere zip_name = 'FullBackup'\r\nand id_elab = (select max(id_elab) from py_monitor.elaborazioni\r\nwhere script_name = 'automated-backup')"
    }
   ]
  },
  {
   "title": "Last Run",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n    CASE \r\n        WHEN esito = '0' THEN 'Success'\r\n        ELSE 'Error'\r\n        END AS decoded_status\r\nFROM \r\n    py_monitor.elaborazioni\r\nWHERE \r\n    script_name = 'automated-backup'\r\nORDER BY \r\n    data_fine DESC\r\nLIMIT 1;\r\n"
    }
   ]
  },
  {
   "title": "Zips Dimension",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "rawSql": "SELECT e.data_iniz AS time, s.zip_name AS metric, s.size AS value\nFROM py_monitor.elaborazioni_size s\nJOIN py_monitor.elaborazioni e ON s.id_elab = e.id_elab\nORDER BY e.data_iniz ASC;"
    }
   ]
  },
  {
   "title": "Last Executions",
   "type": "table",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 11 },
   "targets": [
    {
     "rawSql": "select TO_CHAR(data_iniz, 'DD/MM/YYYY HH24:MI') as DataExec, EXTRACT(MINUTE FROM data_fine - data_iniz) || ' min '||\r\n    round(EXTRACT(SECOND FROM data_fine - data_iniz),0) || ' sec' as TimeRun, \r\n\tCASE \r\n        WHEN esito = '0' THEN 'Success'\r\n        ELSE 'Error'\r\n        END AS status\r\nfrom py_monitor.elaborazioni\r\nwhere script_name = 'automated-backup'\r\norder by data_iniz desc\r\nlimit 10"
    }
   ]
  },
  {
   "title": "Last Executions time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 17, "x": 7, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "SELECT \r\n    data_iniz AS DataExec, \r\n    EXTRACT(EPOCH FROM (data_fine - data_iniz)) AS TimeRunSeconds\r\nFROM py_monitor.elaborazioni\r\nWHERE script_name = 'automated-backup'\r\nORDER BY data_iniz DESC"
    }
   ]
  }
 ]
}